import platform

from .ACPExecutionResourceProvider import ACPExecutionResourceProvider
from .BashExecutionResourceProvider import BashExecutionResourceProvider
from .MCPExecutionResourceProvider import MCPExecutionResourceProvider
from .PythonExecutionResourceProvider import PythonExecutionResourceProvider
from .NodeExecutionResourceProvider import NodeExecutionResourceProvider
from .DockerExecutionResourceProvider import DockerExecutionResourceProvider
from .BrowserExecutionResourceProvider import BrowserExecutionResourceProvider
from .SQLiteExecutionResourceProvider import SQLiteExecutionResourceProvider

# Seatbelt is macOS-only; only import when running on Darwin
if platform.system() == "Darwin":
    from .SeatbeltExecutionResourceProvider import SeatbeltExecutionResourceProvider
